<?xml version="1.0" encoding="UTF-8"?><testrun duration="11028" footerText="Generated by PyCharm on 21.05.2020, 0:37" name="Unittests in unittest_SendJSONForCheck.py">
    <count name="total" value="7"/>
    <count name="failed" value="1"/>
    <count name="passed" value="6"/>
    <config nameIsGenerated="true" configId="tests" name="Unittests in unittest_SendJSONForCheck.py">
        <module name="сервер клиент"/>
        <option name="INTERPRETER_OPTIONS" value=""/>
        <option name="PARENT_ENVS" value="true"/>
        <option name="SDK_HOME" value=""/>
        <option name="WORKING_DIRECTORY" value="D:/Program Files (x86)/PyCharm Community Edition 2019.3.3/сервер клиент"/>
        <option name="IS_MODULE_SDK" value="true"/>
        <option name="ADD_CONTENT_ROOTS" value="true"/>
        <option name="ADD_SOURCE_ROOTS" value="true"/>
        <option name="_new_additionalArguments" value="&quot;&quot;"/>
        <option name="_new_target" value="&quot;D:/Program Files (x86)/PyCharm Community Edition 2019.3.3/сервер клиент/unittest_SendJSONForCheck.py&quot;"/>
        <option name="_new_targetType" value="&quot;PATH&quot;"/>
    </config>
    <suite duration="11028" locationUrl="python&lt;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент&gt;://unittest_SendJSONForCheck" name="unittest_SendJSONForCheck" status="failed">
        <suite duration="11028" locationUrl="python&lt;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент&gt;://unittest_SendJSONForCheck.TestSendJSONForCheck" name="TestSendJSONForCheck" status="failed">
            <test duration="9" locationUrl="python&lt;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент&gt;://unittest_SendJSONForCheck.TestSendJSONForCheck.test_S_5_t1" name="test_S_5_t1 (Код статус не равен 20)" status="passed">
                <output type="stderr">D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:45: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Server.txt&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:45: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Port.json&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
</output>
            </test>
            <test duration="1001" locationUrl="python&lt;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент&gt;://unittest_SendJSONForCheck.TestSendJSONForCheck.test_S_5_t2" name="test_S_5_t2 (Сервер для проверки работы не доступен)" status="passed">
                <output type="stderr">D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:91: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Server.txt&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:91: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Port.json&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:91: ResourceWarning: unclosed &amp;lt;socket.socket fd=380, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=(&amp;#39;0.0.0.0&amp;#39;, 64152)&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
</output>
            </test>
            <test duration="10002" locationUrl="python&lt;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент&gt;://unittest_SendJSONForCheck.TestSendJSONForCheck.test_S_5_t3" name="test_S_5_t3 (Сервер не отвечает в течение 10 секунд)" status="passed">
                <output type="stderr">D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:137: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Server.txt&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:137: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Port.json&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
</output>
            </test>
            <test duration="3" locationUrl="python&lt;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент&gt;://unittest_SendJSONForCheck.TestSendJSONForCheck.test_S_5_t4" name="test_S_5_t4 (Ответ от сервера messageType == 2, grade == 1)" status="passed">
                <output type="stderr">D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:183: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Server.txt&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:183: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Port.json&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
</output>
            </test>
            <test duration="7" locationUrl="python&lt;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент&gt;://unittest_SendJSONForCheck.TestSendJSONForCheck.test_S_5_t5" name="test_S_5_t5 (Ответ от сервера messageType == 2, grade == 0)" status="failed">
                <output type="stderr">D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:229: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Server.txt&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:229: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Port.json&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
False != True
</output>
                <output type="stdout">Expected :
</output>
                <output type="stderr">True
</output>
                <output type="stdout">Actual   :
</output>
                <diff actual="False" expected="True"/>
                <output type="stderr">False
Traceback (most recent call last):
  File &amp;quot;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\plugins\python-ce\helpers\pycharm\teamcity\diff_tools.py&amp;quot;, line 32, in _patched_equals
    old(self, first, second, msg)
  File &amp;quot;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\Python\Python38\lib\unittest\case.py&amp;quot;, line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File &amp;quot;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\Python\Python38\lib\unittest\case.py&amp;quot;, line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: True != False
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File &amp;quot;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\Python\Python38\lib\unittest\case.py&amp;quot;, line 60, in testPartExecutor
    yield
  File &amp;quot;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\Python\Python38\lib\unittest\case.py&amp;quot;, line 676, in run
    self._callTestMethod(testMethod)
  File &amp;quot;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\Python\Python38\lib\unittest\case.py&amp;quot;, line 633, in _callTestMethod
    method()
  File &amp;quot;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py&amp;quot;, line 242, in test_S_5_t5
    self.assertEqual(letters_expectation[0].IsOK, letterRes.IsOK)
</output>
            </test>
            <test duration="3" locationUrl="python&lt;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент&gt;://unittest_SendJSONForCheck.TestSendJSONForCheck.test_S_5_t6" name="test_S_5_t6 (Ответ от сервера messageType == 3)" status="passed">
                <output type="stderr">D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:275: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Server.txt&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:275: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Port.json&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
</output>
            </test>
            <test duration="3" locationUrl="python&lt;D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент&gt;://unittest_SendJSONForCheck.TestSendJSONForCheck.test_S_5_t7" name="test_S_5_t7 (Ответ от сервера messageType == 4)" status="passed">
                <output type="stderr">D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:321: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Server.txt&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:321: ResourceWarning: unclosed file &amp;lt;_io.TextIOWrapper name=&amp;#39;config_Port.json&amp;#39; mode=&amp;#39;r&amp;#39; encoding=&amp;#39;cp1251&amp;#39;&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
D:\Program Files (x86)\PyCharm Community Edition 2019.3.3\сервер клиент\unittest_SendJSONForCheck.py:321: ResourceWarning: unclosed &amp;lt;socket.socket fd=388, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=(&amp;#39;192.168.0.106&amp;#39;, 64158), raddr=(&amp;#39;192.168.0.106&amp;#39;, 10005)&amp;gt;
  letters_expectation = main_2_base_WorkWithLetters.SendJSONForCheck(jsonDates, letters)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
</output>
            </test>
        </suite>
    </suite>
</testrun>
